[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
type = "web"
plan = "free"
startCommand = "node server.js"